defect/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dash_list'),
    path('defect_list/<int:page>/', views.defect_list, name='def_list'),
    path('category_list/', views.category_list, name='cat_list'),
    path('dashboard/', views.dashboard, name='dash_list'),
    path('log_defect/', views.log_defect, name='log_def'),
    path('<int:defect_id>/', views.defect_detail, name='def_detail'),
    path(
        '<int:defect_id>/edit_update/<str:update_id>',
        views.update_edit, name='upd_edit'),
    path(
        '<int:defect_id>/delete_update/<str:update_id>',
        views.update_delete, name='upd_delete'),
]

part/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('defect/', include('defect.urls'), name='defect-urls'),
    path("accounts/", include("allauth.urls"), name='admin_urls'),
    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
    path('', include('defect.urls'), name='home')

]

handler404 = 'defect.views.custom_404'
handler500 = 'defect.views.custom_500'

defect/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


STATUS = ((0, "Open"), (1, "Resolved"))


def get_null_category():
    return Category.objects.get_or_create(name='Null')


class Category(models.Model):
    """
    Stores a single category.
    """
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    fa_string = models.SlugField(max_length=100)
    colour = models.CharField(max_length=7)

    def __str__(self):
        return f"Category: {self.name}"


class Defect(models.Model):
    """
    Stores a single defect, related to :model:'Category' and :model:'auth.User'
    """
    defect_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200, unique=True)
    excerpt = models.CharField(max_length=30, blank=True)
    trunc_title = models.CharField(max_length=30, blank=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="defects")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="defects")
    body = models.TextField()
    image_url = CloudinaryField('image', default='placeholder', blank=True)
    reported_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    reoccurance = models.IntegerField(default=0)
    updates_count = models.IntegerField(default=0)
    latest_update = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-reported_on"]

    def __str__(self):
        return f"Defect: {self.title} ({self.category})"


class Update(models.Model):
    """
    Stores a single update to a defect, related to :model:'Defect'
    and :model:'auth.User'
    """
    update_id = models.AutoField(primary_key=True)
    defect = models.ForeignKey(
        Defect, on_delete=models.CASCADE, related_name="updates")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="updates")
    created_on = models.DateTimeField(auto_now_add=True)
    body = models.TextField()
    excerpt = models.CharField(max_length=30, blank=True)
    image_url = CloudinaryField('image', default='placeholder', blank=True)
    resolution = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ["-created_on"]

defect/forms.py
from cloudinary.forms import CloudinaryFileField
from cloudinary.models import CloudinaryField
from django import forms
from .models import Update, Defect, Category


class CategoryForm(forms.ModelForm):
    """
    Form class for users to add categories
    """
    class Meta:
        """
        Specify the django model and order of the fields
        """
        model = Category
        fields = ('name', 'description', 'fa_string', 'colour')


class DefectForm(forms.ModelForm):
    """
    Form class for users to log new defects
    """
    class Meta:
        """
        Specify the django model and order of the fields
        """
        model = Defect
        fields = ('category', 'title', 'body', 'image_url')


class UpdateForm(forms.ModelForm):
    """
    Form class for users to add new updates
    """
    class Meta:
        """
        Specify the django model and order of the fields
        """
        model = Update
        fields = ('body', 'image_url', 'resolution')

defect/views.py
import cloudinary
from django.shortcuts import render, get_object_or_404, reverse
from django.core.paginator import Paginator, EmptyPage
from django.views import generic
from django.template import RequestContext
from django.contrib import messages
from django.contrib.auth.models import User, Group, Permission
from django.http import HttpResponseRedirect
from cloudinary.forms import cl_init_js_callbacks
from .models import Defect, Category, Update
from .forms import UpdateForm, DefectForm, CategoryForm


def defect_list(request, page=1):
    """
    Renders a filtered list of defects in :model:`defect` depending on
    the GET request and displays them in a page of 15.

    **Context**

    ``defects``
        The filtered instances of :model:`defect.Defect`.
    ``categories``
        All instances of :model:`defect.Categories`.
    ``users``
        All instances of :model:`auth.User`.
    ``prefill``
        Previously selected filter criteria.

    **Template**

    :template:`defect/defect_list.html`
    """
    users = User.objects.all()
    defects = Defect.objects.all()
    categories = Category.objects.all()
    title_contains = request.GET.get('title_contains')
    body_contains = request.GET.get('body_contains')
    category_is = request.GET.get('category')
    status_is = request.GET.get('status')
    author_is = request.GET.get('author')
    sort_by = request.GET.get('date_sort')
    if title_contains is None:
        title_contains = ''
    if body_contains is None:
        body_contains = ''
    if title_contains != '' and title_contains is not None:
        defects = defects.filter(title__icontains=title_contains)
    if body_contains != '' and body_contains is not None:
        defects = defects.filter(body__icontains=body_contains)
    if category_is != '' and category_is != 'all' and category_is is not None:
        defects = defects.filter(category=category_is)
    if status_is != '' and status_is != 'all' and category_is is not None:
        defects = defects.filter(status=status_is)
    if author_is != '' and author_is != 'all' and author_is is not None:
        defects = defects.filter(author=author_is)
    if sort_by != '' and sort_by is not None:
        if sort_by == 'asc':
            defects = defects.order_by('reported_on')
        if sort_by == 'dsc':
            defects = defects.order_by('-reported_on')

    paginator = Paginator(defects, 15)

    try:
        defects = paginator.page(page)
    except EmptyPage:
        defects = paginator.page(paginator.num_pages)

    if category_is != 'all' and category_is is not None:
        category_is = int(category_is)
    if status_is != 'all' and status_is is not None:
        status_is = int(status_is)
    if author_is != 'all' and author_is is not None:
        author_is = int(author_is)

    prefill = {
        'category_is': category_is,
        'title_contains': title_contains,
        'body_contains': body_contains,
        'author_is': author_is,
        'status_is': status_is,
        'sort_by': sort_by,
    }

    context = {
        'defects': defects,
        'categories': categories,
        'users': users,
        'prefill': prefill,
    }
    return render(
        request, 'defect/defect_list.html', context)


def dashboard(request):
    """
    Renders the last 5 instances of :model:`defect.Defect` and the last 5
    instances of :model:`defect.Update`.

    **Context**
    ``defects``
        The last 5 instances of :model:`defect.Defect`.
    ``updates``
        The last 5 instances of :model:`defect.Update`.
    **Template**
    :template:`defect/dash.html`
    """
    defects = Defect.objects.filter(status=0).order_by("-reported_on")[:5]
    updates = Update.objects.all().order_by("-created_on")[:5]
    context = {
        'defects': defects,
        'updates': updates,
    }
    return render(
        request, 'defect/dash.html', context)


def defect_detail(request, defect_id):
    """
    Renders an individual instance of :model:`defect.Defect` and related instances
    of :model:`defect.Update` with a form for adding a new instance of
    :model:`defect.Update`.

    **Context**

    ``defect``
        An instance of :model:`defect.Defect`.
    ``updates``
        All instances of :model:`defect.Update` related to the defect.
    ``update_count``
        A count of updates for this defect.
    ``update_form``
        An instance of :form:`defect.UpdateForm`.
    ``update_latest``
        The last instance of :model:`defect.Update` related to the defect.

    **Template**

    :template:`defect/defect_detail.html`
    """
    defect = get_object_or_404(Defect.objects.all(), defect_id=defect_id)
    updates = defect.updates.all().order_by("created_on")
    update_count = defect.updates.count()
    update_latest = updates.all().last()
    if request.method == "POST":
        update_form = UpdateForm(request.POST, request.FILES)
        if update_form.is_valid():
            update = update_form.save(commit=False)
            update.author = request.user
            update.defect = defect
            if len(update.body) > 30:
                update.excerpt = update.body[:27] + "..."
            else:
                update.excerpt = update.body
            defect.status = update.resolution
            defect.save()
            update.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Update submitted'
            )

    update_form = UpdateForm()

    return render(
        request,
        'defect/defect_detail.html',
        {
            'defect': defect,
            'updates': updates,
            'update_count': update_count,
            'update_form': update_form,
            'update_latest': update_latest,
        },)


def update_edit(request, defect_id, update_id):
    """
    Display an individual update for edit.

    **Context**

    ``defect``
        An instance of :model:`defect.Defect`.
    ``updates``
        All instances of :model:`defect.Update` related to the defect.
    ``update_form``
        An instance of :form:`defect.UpdateForm`.
    """
    if request.method == 'POST':
        update = get_object_or_404(Update, pk=update_id)
        defect = update.defect
        update_form = UpdateForm(data=request.POST, instance=update)

        if update_form.is_valid() and update.author == request.user:
            update = update_form.save(commit=False)
            update.defect = defect
            update.save()
            messages.add_message(
                request, messages.SUCCESS, 'Update successfully edited!')
        else:
            messages.add_message(
                request, messages.ERROR, 'Error editing update!')

    return HttpResponseRedirect(reverse('def_detail', args=[defect_id]))


def update_delete(request, defect_id, update_id):
    """
    Delete an individual update.

    **Context**

    ``defect``
        An instance of :model:`defect.Defect`.
    ``updates``
        All instances of :model:`defect.Update` related to the defect.

    **Template**

    """
    defect = get_object_or_404(Defect, defect_id=defect_id)
    update = get_object_or_404(Update, pk=update_id)

    if update.author == request.user:
        update.delete()
        messages.add_message(request, messages.SUCCESS, 'Update deleted!')
    else:
        messages.add_message(
            request, messages.ERROR, 'You can only delete your own updates!')

    return HttpResponseRedirect(reverse('def_detail', args=[defect_id]))


def log_defect(request):
    """
    Render a form for adding an instance of :model:`defect.Defect`.

    **Context**

    ``categories``
        All instances of :model:`defect.Category`.
    ``defect_form``
        An instance of :form:`defect.DefectForm`.

    **Template**

    :template:`defect/log_defect.html`
    """
    categories = Category.objects.all()

    if request.method == "POST":
        defect_form = DefectForm(request.POST, request.FILES)
        if defect_form.is_valid():
            defect = defect_form.save(commit=False)
            defect.author = request.user
            if len(defect.body) > 30:
                defect.excerpt = defect.body[:27] + "..."
            else:
                defect.excerpt = defect.body
            if len(defect.title) > 30:
                defect.trunc_title = defect.title[:27] + "..."
            else:
                defect.trunc_title = defect.title
            defect.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Defect logged'
            )

    defect_form = DefectForm()

    return render(
        request,
        'defect/log_defect.html',
        {
            'categories': categories,
            'defect_form': defect_form,
        },
    )


def category_list(request):
    """
    Renders a list of all instances of :model:`defect.Category` with
    a form to add more.

    **Context**

    ``categories``
        All instances of :model:`defect.category`.
    ``category_form``
        An instance of :forms:`defect.CategoryForm`.
    **Template**

    :template:`defect/category_list.html`
    """
    categories = Category.objects.all()

    if request.method == "POST":
        category_form = CategoryForm(data=request.POST)
        if category_form.is_valid():
            category = category_form.save(commit=False)
            category.save()
            messages.add_message(
                request, messages.SUCCESS,
                'New category successfully added'
            )
    category_form = CategoryForm()

    return render(
        request,
        'defect/category_list.html',
        {
            'categories': categories,
            'category_form': category_form,
        },
    )


def custom_404(request, exception):
    """
    Renders a custom 404 page

    **Template**

    :template:`404.html`
    """
    return render(request, '404.html', status=404)


def custom_500(request):
    """

defect/templates/defect/category_list.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% if user.is_authenticated and perms.defect.view_defect and perms.defect.view_update %}
<div class="container-lg">
    <div class="row mt-3">
        <div class="col">
            <h2>Category List</h2>
        </div>
    </div>
    <div class="row border border-secondary rounded bg-white -mt-3">
        <div class="col">
            {% for category in categories %}
            <div class="row mt-2">
                <div class="col-2"><p><i class="fa-solid {{category.fa_string}} fa-icon-lg" style="color:{{ category.colour }};"></i></p></div> 
                <div class="col-3"><p>{{category.name}}</p></div>
                <div class="col-7"><p>{{category.description | safe }}</p></div>
                
            </div>
            {% endfor %}
        </div>
    </div>
    {% if user.is_authenticated and perms.defect.add_category %}
    <div class="row mt-5">
        <div class="col">
            <h2>Add category</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form id="CategoryForm" method="post" style="margin-top: 1.3em;">
                {{ category_form | crispy }}
                {% csrf_token %}
                <div class="col text-center">
                <button id="submitButton" type="submit" class="btn btn-primary btn-blue btn-lg mb-5">Submit</button>
            </div>
                </form>
        </div>
    </div>
    {% endif %}
</div>

        
    
   
{% endif %}
{% endblock %}

defect/templates/defect/dash.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- not logged logged in-->
{% if not user.is_authenticated %}
<div class="container-lg">
<div class="card">
    <div class="card-body text-center">
      <h2 class="card-title">{% if user.is_authenticated %}You are logged in as {{ user }}.{% else %}You are not logged in{% endif %}</h2>
      <a href="{% url 'account_login' %}" class="btn btn-primary btn-blue">Login</a>
      <a href="{% url 'account_signup' %}" class="btn btn-secondary">Register</a>
    </div>
  </div>
</div>
{% endif %}
<!-- logged in-->
{% if user.is_authenticated and perms.defect.view_defect and perms.defect.view_update %}
<div class="container-lg">
    <div class="row">
        <div class="col px-0">
            <h2 class="text-center">Recent Defects</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-1 pl-1 pr-0 py-1">
            <p><i class="fa-solid fa-flag"></i></p>
        </div>
        <div class="col-1 px-0 py-1">
            <p><i class="fa-solid fa-comment"></i></p>
        </div>
        
        <div class="col-6 px-0 py-1">
            <p>title</p>
        </div>
        <div class="col-2 px-0 py-1">
            <p><i class="fa-solid fa-calendar-day"></i></p>
        </div>
        <div class="col-2 px-0 py-1">
            <p><i class="fa-solid fa-user"></i></p>
        </div>
    </div>

    <div class="row border border-secondary rounded bg-white my-0">
        <div class="col">
            {% for defect in defects %}
            <div class="row border border-top border-bottom py-0">
            
                <div class="col-1 pl-1 pr-0 py-1">
                    
                    <p class="m-auto"><i class="fa-solid {{defect.category.fa_string}}" style="color: {{ defect.category.colour }};"></i></p>
                    
                </div>
                <div class="col-1 px-0 py-1"><p class="m-auto">{{ defect.updates.count }}</p></div>
                <div class="col-6 px-0 py-1"><a class="text-dark" href="{% url 'def_detail' defect.defect_id %}"><p class="text-truncate m-auto">{{defect.trunc_title}}</p></a></div>    
                <div class="col-2 px-0 py-1"><p class="text-truncate m-auto">{{ defect.reported_on|date:"d/m/Y" }}</p></div>
                <div class="col-2 px-0 py-1"><p class="text-truncate m-auto">{{ defect.author }}</p></div>
            </div>
            {% endfor %}
        </div>
    </div>
    
</div>
<br>
<div class="container-lg">
    <div class="row">
        <div class="col">
            <h2 class="text-center">Recent Updates</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-2 px-0 py-1">
            <p class="text-truncate">defect</p>
        </div>
        <div class="col-1 px-0 py-1">
            <p><i class="fa-solid fa-image"></i></p>
        </div>
        <div class="col-5 px-0 py-1">
            
        </div>
        <div class="col-2 px-0 py-1">
            <p><i class="fa-solid fa-calendar-day"></i></p>
        </div>
        <div class="col px-0 py-1">
            <p><i class="fa-solid fa-user"></i></p>
        </div>
    </div>

    <div class="row border border-secondary rounded bg-white">
        <div class="col">
            {% for update in updates %}
            <div class="row border border-top border-bottom">
            
                <div class="col-2 px-0 py-1"><p class="text-truncate"><a class="text-dark" href="{% url 'def_detail' update.defect.defect_id %}">{{ update.defect.trunc_title }}</a></p></div>
                <div class="col-1 px-0 py-1">
                    {% if "placeholder" in update.image_url.url %}

                    {% else %}
                    <a href="{{ update.image_url.url }}" target="_BLANK" aria-label="Link to image (opens in new tab)."><p><i class="fa-solid fa-image"></i></p></a>
                    {% endif %}
                </div>
                <div class="col-5 px-0 py-1"><a class="text-dark" href="{% url 'def_detail' update.defect.defect_id %}#update_{{ update.update_id }}"><p class="text-truncate">{{update.excerpt}}</p></a></div>    
                <div class="col-2 px-0 py-1"><p class="text-truncate">{{ update.created_on|date:"d/m/Y" }}</p></div>
                <div class="col px-0 py-1"><p class="text-truncate m-auto">{{ update.author }}</p></div>
            </div>
            {% endfor %}
        </div>
    </div>
    
</div>
{% if user.is_authenticated and perms.defect.add_defect %}
<div class="container-lg">
<div class="row">
    <div class="col">
        <br>
        <h2 class="text-center"><a href="{% url 'log_def' %}">Log New Defect</a></h2>
        <br>
    </div>
</div>
</div>
{% endif %}
{% endif %}
{% if user.is_authenticated and not perms.defect.view_defect and not perms.defect.view_update %}
<div class="row">
    <div class="col">
        <p>Your account is pending approval. Contact your administrator if you think this is an error.</p>
    </div>
</div>

{% endif %}
{% endblock %}

defect/templates/defect/defect_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load cloudinary %}   
{% block content %}
{% if user.is_authenticated and perms.defect.view_defect and perms.defect.view_update %}
<div id="defect" class="d-none">{{ defect.defect_id }}</div>
    <div class="container-lg">
        <div class="row border border-secondary rounded bg-white mt-4">
            <div class="col">
                <div class="row justify-content-center-md-center mt-4">
                    <div class="col-2">
                        <p><i class="fa-solid {{defect.category.fa_string}}" style="color: {{ defect.category.colour }}; font-size: 250%;"></i></p>
                    </div>
                    <div class="col-10">
                        <h2 class="text-left">{{ defect.title }}</h2>
                    </div>
                </div>
                <div class="row mb-0">
                    <div class="col">
                        <p class="text-right">Reported {{ defect.reported_on|date:"d/m/Y H:i" }} by {{ defect.author }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row border border-secondary rounded bg-white mt-3">
            <div class="col my-4">
                {{ defect.body | safe }}
            </div>
        </div>
        <div class="row mt-3">
            <div class="col"> 
                <!-- images go here -->
                {% if "placeholder" in defect.image_url.url %}
                <p>No images.</p>
                {% else %}
                <a href="{{ defect.image_url.url }}" aria-label="Link to image for defect (opens in new tab)." target="_BLANK">
                    <div class="col border rounded" style="width: 200px; height: 200px; background-image: url({{ defect.image_url.url }}); overflow: hidden; background-position:center; background-size: cover;" aria-label="image for {{ defect.title }}"></div>
                </a>
                {% endif %}
            </div>
        </div>
        <div class="row mt-4">
            <div class="col">
                <h3>Updates</h3>
                <a class="btn btn-secondary" href="#update_{{update_latest.update_id}}">Latest</a>
            </div>
            <br>
        </div>
        {% for update in updates %}
        <div class="row border border-secondary rounded bg-white mt-4">
            <div class="col">
                <div class="row">
                    <div class="col mx-0">
                        <p class="text-right">{{ update.created_on|date:"d/m/Y H:i" }} by {{ update.author }}</p>
                    </div>
                    <div class="col-1 mx-1">
                        <p class="text-right">{% if update.resolution %}<i class="fa-solid fa-circle-check"></i>{% else %}<i class="fa-regular fa-circle"></i>{% endif %}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col mb-4 mt-2" id="update_{{ update.update_id }}">
                        {{ update.body | safe }}
                    </div>
                </div>
                <hr>
                <div class="row mt-3">
                    <div class="col">
                        <!-- images go here -->
                        {% if "placeholder" in update.image_url.url %}
                        <p>No images.</p>
                        {% else %}
                        <a href="{{ update.image_url.url }}" aria-label="Link to update {{ update.update_id }} image (opens in new tab)." target="_BLANK">
                            <div class="col border rounded mb-2" style="width: 200px; height: 200px; background-image: url({{ update.image_url.url }}); overflow: hidden; background-position:center; background-size: cover;"></div>
                        </a>  
                        {% endif %}
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col text-right">
                        {% if user.is_authenticated and update.author == user or perms.update.change_update %}
                        <button class="btn btn-edit btn-secondary mb-4" data-defect_id="{{ defect.defect_id }}" data-update_id="{{ update.update_id }}">Edit</button>
                        <button class="btn btn-delete btn-danger mb-4" data-defect_id="{{ defect.defect_id }}" data-update_id="{{ update.update_id }}">Delete</button>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="row" id="new_edit">
        <div class="col">
            <!-- new update form -->
            <div class="div my-5">
                <div class="col">
                    {% if user.is_authenticated and perms.defect.add_update %}
                    <h2>New Update</h2>
                    <form id="updateForm" method="post" enctype="multipart/form-data" style="margin-top: 1.3em;">
                    {{ update_form | crispy }}
                    {% csrf_token %}
                    <button id="submitButton" type="submit" class="btn btn-primary  btn-blue btn-signup btn-lg">Submit</button>
                    </form>
                    {% else %}
                    You do not have the required permissions to add updates.
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1"
    aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"
                id="deleteModalLabel">Delete Update?</h5>
                <button type="button" class="btn"
                data-dismiss="modal" aria-label="Close">&times;</button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete your update?
                This action cannot be undone.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary"
                data-dismiss="modal">Close</button>
                <a id="deleteConfirm" href="#" class="btn
                btn-danger">Delete</a>
            </div>
        </div>
    </div>


{% endif %}
{% endblock content %}

{% block extras %}
<script src="{% static 'js/updates.js' %}"></script>
{% endblock %}

defect/templates/defect/log_defect.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container-lg mb-4">
    <div class="row justify-content-center">
        <div class="col">
            {% if user.is_authenticated and perms.defect.add_defect %}
                        <h2 class="text-center mt-4">Log New Defect</h2>
                        <div class="form-group text-center">
                        <form id="DefectForm" method="post" enctype="multipart/form-data" style="margin-top: 1.3em;">
                            {{ defect_form | crispy }}
                            {% csrf_token %}
                            <button id="submitButton" type="submit" class="btn btn-primary btn-blue btn-signup btn-lg">Submit</button>
                            </form>
                        </div>
                        {% else %}
                        You do not have the required authorisation to log defects.
                        {% endif %}
        </div>
    </div>
</div>
{% endblock %}

defect/templates/defect/user_approval.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container-lg">
    <div class="row">
        <div class="col-1">
            <p>Username</p>
        </div>
        <div class="col-1">
            <p>Active</p>
        </div>
        <div class="col-4">
            <p>Level 1</p>
        </div>
        <div class="col-1">
            <p>Level 2</p>
        </div>
        <div class="col-2">
            <p>Level 3</p>
        </div>

        <div class="col-1">
            <p>Approve</p>
        </div>
    </div>
    {% for user in users %}
    <div class="row">
        <div class="col-1">
            {{ user }}
        </div>
        <div class="col-1">
            {{ user.is_active }}
        </div>
        <div class="col-1">
            {% if 'defect.view_defect' in user.get_all_permissions %}
            <p>View Defect</p>
            {% endif %}  
        </div>
        <div class="col-1">
            {% if 'defect.add_defect' in user.get_all_permissions %}
            <p>Add Defect</p>
            {% endif %}  
        </div>
        <div class="col-2">
            {% if 'defect.view_update' in user.get_all_permissions %}
            <p>View Updates</p>
            {% endif %}  
        </div>
        <div class="col-1">
            {% if 'defect.add_update' in user.get_all_permissions %}
            <p>Add Updates</p>
            {% endif %}  
        </div>
        <div class="col-1">
            {% if 'defect.add_category' in user.get_all_permissions %}
            <p>Add Category</p>
            {% endif %}  
        </div>
        <div class="col-1">
            {% if 'auth.change_user' in user.get_all_permissions %}
            <p>Approve Users</p>
            {% endif %}  
        </div>
        <div class="col-1">
            {% if user.is_authenticated and perms.auth.change_user and 'defect.view_defect' not in user.get_all_permissions %}
            <p>Approve</p>
            {% endif %}  
        </div>
        <!--{{ user.get_all_permissions }}-->
    </div>
            

            {% endfor %}
</div>





{% endblock %}